[tool.ruff]
line-length = 79
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 79
extend_skip = ['migrations']

[tool.pytest.ini_options]
pythonpath = "."

[tool.blue]
extend-exclude = '(migrations/)'

[tool.taskipy.tasks]
lint = 'ruff . && blue --check . --diff'
lint_fix = 'ruff . --fix && blue --check . --diff'
checker = 'mypy src/main.py --strict'
format = 'blue .  && isort .'
run = 'uvicorn src.main:app --reload'
pre_test = 'task lint'
unit = 'pytest -s -x -m unit --cov=src -vv'
functional = 'pytest -s -x -m functional --cov=src -vv'
post_test = 'coverage html'
migrate = 'alembic upgrade head'
